### ISSUE TITLE
Error running on Synology DSM6

### ISSUE THREAD

**Issue by ceraz68** [alfredopironti/Paradox_IP150#1]
Hi I trying to run this on a synology NAS. I was on python 2.7 now updated to python 3.5.1 (located in /volume1/@appstore/py3k) and reinstalled the missing modules for successful import. My mitt broker is validated by other devices. Thanks for any pointers.

$ python ip150_mqtt.py /volume1/docker/homebridge/Paradox_IP150-master/options.json

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/volume1/docker/homebridge/Paradox_IP150-master/ip150.py", line 193, in _get_updates
    cur_state = self.get_info()
  File "/volume1/docker/homebridge/Paradox_IP150-master/ip150.py", line 87, in wrapped
    return f(self, *args, **kwargs)
  File "/volume1/docker/homebridge/Paradox_IP150-master/ip150.py", line 185, in get_info
    res[table] = [(i, self._tables_map[table]['map'][x]) for i,x in enumerate(tmp, start=1)]
  File "/volume1/docker/homebridge/Paradox_IP150-master/ip150.py", line 185, in <listcomp>
    res[table] = [(i, self._tables_map[table]['map'][x]) for i,x in enumerate(tmp, start=1)]
KeyError: 8

^C **<= MY CONTROL BREAKPOINT**
Traceback (most recent call last):
  File "ip150_mqtt.py", line 110, in <module>
    ip_mqtt.loop_forever()
  File "ip150_mqtt.py", line 103, in loop_forever
    mqc.loop_forever()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/paho/mqtt/client.py", line 1481, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/paho/mqtt/client.py", line 988, in loop
    socklist = select.select(rlist, wlist, [], timeout)
KeyboardInterrupt

**Comment by alfredopironti** [comment]
Hi,

It seems you were using the Paradox alarm with the instant arm mode, which wasn't supported in the earliest version of this add-on. This functionality should now be supported in the latest revision.

If you're still interested can you try with the latest version and let me know? Thanks.

**Comment by alfredopironti** [comment]
Closing for lack of feedback. The issue should be solved in the latest revision.
